server {
  listen 80;
  server_name _;
  resolver 127.0.0.11 valid=10s ipv6=off;

  root /usr/share/nginx/html;
  index index.html;

  location = /health/ventas {
    set $ventas_health http://backend-ventas:8080/api/health;
    proxy_pass $ventas_health;
  }

  location = /health/despachos {
    set $despachos_health http://backend-despachos:8081/api/health;
    proxy_pass $despachos_health;
  }

  location /api/v1/ventas {
    set $ventas_upstream http://backend-ventas:8080;
    proxy_pass $ventas_upstream;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  location /api/v1/despachos {
    set $despachos_upstream http://backend-despachos:8081;
    proxy_pass $despachos_upstream;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
